all:
  hosts:
  children:
    asa_firewalls:
      hosts:
        cisco-asa-example-1:
          ansible_host: x.x.x.x
          ansible_network_os: asa
   
    switches:
      hosts:
        cisco-switch-example-1:
          ansible_host: x.x.x.x
          ansible_network_os: ios      
